spring.application.name=sucursales

amazon.dynamodb.endpoint=${AMAZON_DYNAMODB_ENDPOINT:https://dynamodb.us-east-2.amazonaws.com}
amazon.aws.region=${AMAZON_AWS_REGION:us-east-2}

server.port=8080

springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
